/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author isado
 */
public class Login extends javax.swing.JFrame {
private User acess = new User();

    /**
     * Creates new form TelaLogin
     */
    public Login() {
        initComponents();
        setTitle("Login");
        getContentPane().setBackground(new Color(235,237,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LoginPassword = new javax.swing.JPasswordField();
        BottonIn = new javax.swing.JButton();
        BottonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livros-tela-login.jpg"))); // NOI18N

        jLabel2.setText("Usuário");

        LoginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha");

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 117, 186));
        jLabel4.setText("EmentorPlus");

        BottonIn.setBackground(new java.awt.Color(243, 243, 243));
        BottonIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-entrar.png"))); // NOI18N
        BottonIn.setText("Entrar");
        BottonIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonInActionPerformed(evt);
            }
        });

        BottonBack.setBackground(new java.awt.Color(243, 243, 243));
        BottonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-voltar.png"))); // NOI18N
        BottonBack.setText("Voltar");
        BottonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BottonBack)
                            .addComponent(BottonIn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BottonIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BottonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginNameActionPerformed

    private void BottonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonBackActionPerformed
        Home acess = new Home();
        acess.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BottonBackActionPerformed

    private void BottonInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonInActionPerformed
        if (LoginName.getText().equals("") || LoginPassword.getText().equals(""))
            JOptionPane.showMessageDialog(null, "O campo de usuário e/ou senha não está preenchido", "Login", WARNING_MESSAGE);
        else {
            ConexaoMySQL conection = new ConexaoMySQL();
            acess = conection.searchUser(LoginName.getText());
            
            if (acess != null){
                if (acess.getSenha().equals(LoginPassword.getText())){
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    
                    if (acess.getTipoAcesso().equals("Administrativo"))
                        menu.Habilitar();
                    
                    setVisible(false);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Senha inválida", "Login", ERROR_MESSAGE);
                    LoginPassword.setText("");                    
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Usuário não encontrado", "Login", ERROR_MESSAGE);
                LoginName.setText("");       
                LoginPassword.setText("");
            }
        }
    }//GEN-LAST:event_BottonInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonBack;
    private javax.swing.JButton BottonIn;
    private javax.swing.JTextField LoginName;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
