/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author isado
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Menu");
        getContentPane().setBackground(new Color(235,237,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        StudentRegistrationBotton = new javax.swing.JButton();
        StudentEditBotton = new javax.swing.JButton();
        StudentListBotton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ProfessorRegistrationBotton = new javax.swing.JButton();
        ProfessorEditBotton = new javax.swing.JButton();
        ProfessorListBotton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        UserEditBotton = new javax.swing.JButton();
        StudentListBotton1 = new javax.swing.JButton();
        ExitBotton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 117, 186));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu de Opçoes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções Estudantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        StudentRegistrationBotton.setBackground(new java.awt.Color(235, 237, 255));
        StudentRegistrationBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-cadastro.png"))); // NOI18N
        StudentRegistrationBotton.setText("Cadastrar");
        StudentRegistrationBotton.setEnabled(false);
        StudentRegistrationBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRegistrationBottonActionPerformed(evt);
            }
        });

        StudentEditBotton.setBackground(new java.awt.Color(235, 237, 255));
        StudentEditBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edição.png"))); // NOI18N
        StudentEditBotton.setText("Editar");
        StudentEditBotton.setEnabled(false);
        StudentEditBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentEditBottonActionPerformed(evt);
            }
        });

        StudentListBotton.setBackground(new java.awt.Color(235, 237, 255));
        StudentListBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista-de-itens.png"))); // NOI18N
        StudentListBotton.setText("Listar");
        StudentListBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentListBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentRegistrationBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentEditBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentListBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(StudentRegistrationBotton)
                .addGap(26, 26, 26)
                .addComponent(StudentEditBotton)
                .addGap(27, 27, 27)
                .addComponent(StudentListBotton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções Professores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        ProfessorRegistrationBotton.setBackground(new java.awt.Color(235, 237, 255));
        ProfessorRegistrationBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-cadastro.png"))); // NOI18N
        ProfessorRegistrationBotton.setText("Cadastrar");
        ProfessorRegistrationBotton.setEnabled(false);
        ProfessorRegistrationBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorRegistrationBottonActionPerformed(evt);
            }
        });

        ProfessorEditBotton.setBackground(new java.awt.Color(235, 237, 255));
        ProfessorEditBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edição.png"))); // NOI18N
        ProfessorEditBotton.setText("Editar");
        ProfessorEditBotton.setEnabled(false);
        ProfessorEditBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorEditBottonActionPerformed(evt);
            }
        });

        ProfessorListBotton.setBackground(new java.awt.Color(235, 237, 255));
        ProfessorListBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista-de-itens.png"))); // NOI18N
        ProfessorListBotton.setText("Listar");
        ProfessorListBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorListBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfessorRegistrationBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfessorEditBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfessorListBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ProfessorRegistrationBotton)
                .addGap(26, 26, 26)
                .addComponent(ProfessorEditBotton)
                .addGap(28, 28, 28)
                .addComponent(ProfessorListBotton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        UserEditBotton.setBackground(new java.awt.Color(235, 237, 255));
        UserEditBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edição.png"))); // NOI18N
        UserEditBotton.setText("Editar");
        UserEditBotton.setEnabled(false);
        UserEditBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEditBottonActionPerformed(evt);
            }
        });

        StudentListBotton1.setBackground(new java.awt.Color(235, 237, 255));
        StudentListBotton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista-de-itens.png"))); // NOI18N
        StudentListBotton1.setText("Listar");
        StudentListBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentListBotton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserEditBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentListBotton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(UserEditBotton)
                .addGap(26, 26, 26)
                .addComponent(StudentListBotton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ExitBotton.setBackground(new java.awt.Color(235, 237, 255));
        ExitBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-sair.png"))); // NOI18N
        ExitBotton.setText("Sair");
        ExitBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExitBotton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ExitBotton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void Habilitar(){
        StudentRegistrationBotton.setEnabled(true);
        ProfessorRegistrationBotton.setEnabled(true);
        StudentEditBotton.setEnabled(true);
        ProfessorEditBotton.setEnabled(true);
        UserEditBotton.setEnabled(true);
    }
    
    
    private void StudentRegistrationBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRegistrationBottonActionPerformed
        StudentRegistration acesso = new StudentRegistration();
        acesso.setVisible(true);
    }//GEN-LAST:event_StudentRegistrationBottonActionPerformed

    private void ProfessorRegistrationBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorRegistrationBottonActionPerformed
        ProfessorRegistration acesso = new ProfessorRegistration();
        acesso.setVisible(true);
    }//GEN-LAST:event_ProfessorRegistrationBottonActionPerformed

    private void StudentEditBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentEditBottonActionPerformed
        StudentEdit acesso = new StudentEdit();
        acesso.setVisible(true);
    }//GEN-LAST:event_StudentEditBottonActionPerformed

    private void StudentListBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentListBottonActionPerformed
        StudentList acesso = new StudentList();
        acesso.setVisible(true);
    }//GEN-LAST:event_StudentListBottonActionPerformed

    private void ProfessorEditBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorEditBottonActionPerformed
        ProfessorEdit acesso = new ProfessorEdit();
        acesso.setVisible(true);
    }//GEN-LAST:event_ProfessorEditBottonActionPerformed

    private void ProfessorListBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorListBottonActionPerformed
        ProfessorList acesso = new ProfessorList();
        acesso.setVisible(true);
    }//GEN-LAST:event_ProfessorListBottonActionPerformed

    private void UserEditBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEditBottonActionPerformed
        UserEdit acesso = new UserEdit();
        acesso.setVisible(true);
    }//GEN-LAST:event_UserEditBottonActionPerformed

    private void StudentListBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentListBotton1ActionPerformed
        UserList acesso = new UserList();
        acesso.setVisible(true);
    }//GEN-LAST:event_StudentListBotton1ActionPerformed

    private void ExitBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBottonActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Deseja sair do EmentorPlus ?", "EmentorPlus", YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Até breve!", "EmentorPlus", PLAIN_MESSAGE);
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_ExitBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBotton;
    private javax.swing.JButton ProfessorEditBotton;
    private javax.swing.JButton ProfessorListBotton;
    private javax.swing.JButton ProfessorRegistrationBotton;
    private javax.swing.JButton StudentEditBotton;
    private javax.swing.JButton StudentListBotton;
    private javax.swing.JButton StudentListBotton1;
    private javax.swing.JButton StudentRegistrationBotton;
    private javax.swing.JButton UserEditBotton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
