/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author isado
 */
public class ProfessorRegistration extends javax.swing.JFrame {
private People person = new People();

    /**
     * Creates new form StudentRegistration
     */
    public ProfessorRegistration() {
        initComponents();
        setTitle("Cadastro de Professor");
        getContentPane().setBackground(new Color(235,237,255));
        
        Professor person = new Professor();
        ProfessorRecord.setText(person.createRecord());
        ProfessorAdmissionDate.setText(person.getDateTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ProfessorName = new javax.swing.JTextField();
        BothParents = new javax.swing.JRadioButton();
        Mother = new javax.swing.JRadioButton();
        Father = new javax.swing.JRadioButton();
        ProfessorMotherName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ProfessorFatherName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ProfessorBirthday = new javax.swing.JFormattedTextField();
        ProfessorCPF = new javax.swing.JFormattedTextField();
        ProfessorPhone = new javax.swing.JFormattedTextField();
        NextButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ProfessorRecord = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        ProfessorSalary = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        ProfessorSubject = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        ProfessorAdmissionDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 117, 186));
        jLabel1.setText("Cadastro de Professor(a)");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel22.setForeground(new java.awt.Color(240, 0, 0));
        jLabel22.setText("*");

        jLabel25.setText("Nome Completo:");

        jLabel23.setForeground(new java.awt.Color(240, 0, 0));
        jLabel23.setText("*");

        jLabel27.setText("Data Nascimento:");

        jLabel24.setForeground(new java.awt.Color(240, 0, 0));
        jLabel24.setText("*");

        jLabel18.setText("CPF:");

        jLabel26.setForeground(new java.awt.Color(240, 0, 0));
        jLabel26.setText("*");

        jLabel19.setText("Telefone/Celular:");

        BothParents.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(BothParents);
        BothParents.setText("Pai e Mãe");
        BothParents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BothParentsMouseClicked(evt);
            }
        });
        BothParents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BothParentsActionPerformed(evt);
            }
        });

        Mother.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Mother);
        Mother.setText("Apenas Mãe");
        Mother.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MotherMouseClicked(evt);
            }
        });
        Mother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherActionPerformed(evt);
            }
        });

        Father.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Father);
        Father.setText("Apenas Pai");
        Father.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FatherMouseClicked(evt);
            }
        });

        ProfessorMotherName.setEnabled(false);

        jLabel28.setText("Nome da Mãe:");
        jLabel28.setEnabled(false);

        jLabel29.setForeground(new java.awt.Color(240, 0, 0));
        jLabel29.setText("*");
        jLabel29.setEnabled(false);

        ProfessorFatherName.setEnabled(false);

        jLabel30.setText("Nome do Pai:");
        jLabel30.setEnabled(false);

        jLabel31.setForeground(new java.awt.Color(240, 0, 0));
        jLabel31.setText("*");
        jLabel31.setEnabled(false);

        jLabel32.setText("Selecione uma opção:");

        try {
            ProfessorBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ProfessorCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ProfessorPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProfessorFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BothParents)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel19))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel32)
                                    .addComponent(ProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(ProfessorBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(ProfessorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(ProfessorCPF)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Mother)
                                    .addGap(37, 37, 37)
                                    .addComponent(Father))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel28)
                                        .addComponent(ProfessorMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BothParents)
                    .addComponent(Mother)
                    .addComponent(Father))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel23)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfessorBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfessorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel26))
                .addGap(3, 3, 3)
                .addComponent(ProfessorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        NextButton.setBackground(new java.awt.Color(243, 243, 243));
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-concluido.png"))); // NOI18N
        NextButton.setText("Salvar");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(243, 243, 243));
        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-cancelar.png"))); // NOI18N
        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Escolares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel33.setForeground(new java.awt.Color(240, 0, 0));
        jLabel33.setText("*");

        jLabel34.setText("Matrícula:");

        jLabel37.setForeground(new java.awt.Color(240, 0, 0));
        jLabel37.setText("*");

        ProfessorRecord.setEditable(false);

        jLabel44.setText("Data Admissão:");

        jLabel45.setText("Salário:");

        jLabel46.setForeground(new java.awt.Color(240, 0, 0));
        jLabel46.setText("*");

        jLabel36.setForeground(new java.awt.Color(240, 0, 0));
        jLabel36.setText("*");

        jLabel35.setText("Disciplina:");

        try {
            ProfessorAdmissionDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel34)
                                .addComponent(ProfessorRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35)
                                .addComponent(ProfessorSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel46)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel45)
                                .addComponent(ProfessorSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ProfessorAdmissionDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel44))
                .addGap(12, 12, 12)
                .addComponent(ProfessorAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProfessorSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextButton)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelButton)
                    .addComponent(NextButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BothParentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BothParentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BothParentsActionPerformed

    private void MotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotherActionPerformed

    private void BothParentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BothParentsMouseClicked
        jLabel28.setEnabled(true);
        jLabel29.setEnabled(true);
        ProfessorMotherName.setEnabled(true);
        jLabel30.setEnabled(true);
        jLabel31.setEnabled(true);
        ProfessorFatherName.setEnabled(true);
    }//GEN-LAST:event_BothParentsMouseClicked

    private void MotherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotherMouseClicked
        jLabel28.setEnabled(true);
        jLabel29.setEnabled(true);
        ProfessorMotherName.setEnabled(true);
        jLabel30.setEnabled(false);
        jLabel31.setEnabled(false);
        ProfessorFatherName.setEnabled(false);
    }//GEN-LAST:event_MotherMouseClicked

    private void FatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FatherMouseClicked
        jLabel28.setEnabled(false);
        jLabel29.setEnabled(false);
        ProfessorMotherName.setEnabled(false);
        jLabel30.setEnabled(true);
        jLabel31.setEnabled(true);
        ProfessorFatherName.setEnabled(true);
    }//GEN-LAST:event_FatherMouseClicked

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if (BothParents.isSelected()){
            if (ProfessorName.getText().equals("") || ProfessorMotherName.getText().equals("") || ProfessorFatherName.getText().equals("") || ProfessorBirthday.getText().equals("") || ProfessorCPF.getText().equals("") || ProfessorPhone.getText().equals("") || ProfessorSubject.getText().equals("") || ProfessorRecord.getText().equals("") || ProfessorAdmissionDate.getText().equals("") || ProfessorSalary.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Cadastro Professor", WARNING_MESSAGE);
            }
            else {
                ConexaoMySQL conection = new ConexaoMySQL();
                person = conection.searchPeople(ProfessorCPF.getText()); 
                if (person == null){
                    conection.insertProfessor(ProfessorName.getText(), ProfessorMotherName.getText(), ProfessorFatherName.getText(), ProfessorBirthday.getText(), ProfessorCPF.getText(), ProfessorPhone.getText(), ProfessorSubject.getText(), ProfessorRecord.getText(), ProfessorAdmissionDate.getText(), Double.parseDouble(ProfessorSalary.getText()));
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso", "Cadastro Professor", INFORMATION_MESSAGE);
                    setVisible(false);
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!", "Cadastro Professor", ERROR_MESSAGE);
                }
            }
        }
        else if (Mother.isSelected()){
            if (ProfessorName.getText().equals("") || ProfessorMotherName.getText().equals("") || ProfessorBirthday.getText().equals("") || ProfessorCPF.getText().equals("") || ProfessorPhone.getText().equals("") || ProfessorSubject.getText().equals("") || ProfessorRecord.getText().equals("") || ProfessorAdmissionDate.getText().equals("") || ProfessorSalary.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Cadastro Professor", WARNING_MESSAGE);
            }
            else {
                ConexaoMySQL conection = new ConexaoMySQL();
                person = conection.searchPeople(ProfessorCPF.getText()); 
                if (person == null){
                    conection.insertProfessor(ProfessorName.getText(), ProfessorMotherName.getText(), ProfessorFatherName.getText(), ProfessorBirthday.getText(), ProfessorCPF.getText(), ProfessorPhone.getText(), ProfessorSubject.getText(), ProfessorRecord.getText(), ProfessorAdmissionDate.getText(), Double.parseDouble(ProfessorSalary.getText()));
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso", "Cadastro Professor", INFORMATION_MESSAGE);
                    setVisible(false);
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!", "Cadastro Professor", ERROR_MESSAGE);
                }
            }
        }
        else if (Father.isSelected()){
            if (ProfessorName.getText().equals("") || ProfessorFatherName.getText().equals("") || ProfessorBirthday.getText().equals("") || ProfessorCPF.getText().equals("") || ProfessorPhone.getText().equals("") || ProfessorSubject.getText().equals("") || ProfessorRecord.getText().equals("") || ProfessorAdmissionDate.getText().equals("") || ProfessorSalary.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Cadastro Professor", WARNING_MESSAGE);
            }
            else {
                ConexaoMySQL conection = new ConexaoMySQL();
                person = conection.searchPeople(ProfessorCPF.getText()); 
                if (person == null){
                    conection.insertProfessor(ProfessorName.getText(), ProfessorMotherName.getText(), ProfessorFatherName.getText(), ProfessorBirthday.getText(), ProfessorCPF.getText(), ProfessorPhone.getText(), ProfessorSubject.getText(), ProfessorRecord.getText(), ProfessorAdmissionDate.getText(), Double.parseDouble(ProfessorSalary.getText()));
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso", "Cadastro Professor", INFORMATION_MESSAGE);
                    setVisible(false);
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!", "Cadastro Professor", ERROR_MESSAGE);
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Cadastro Professor", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_NextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BothParents;
    private javax.swing.JButton CancelButton;
    private javax.swing.JRadioButton Father;
    private javax.swing.JRadioButton Mother;
    private javax.swing.JButton NextButton;
    private javax.swing.JFormattedTextField ProfessorAdmissionDate;
    private javax.swing.JFormattedTextField ProfessorBirthday;
    private javax.swing.JFormattedTextField ProfessorCPF;
    private javax.swing.JTextField ProfessorFatherName;
    private javax.swing.JTextField ProfessorMotherName;
    private javax.swing.JTextField ProfessorName;
    private javax.swing.JFormattedTextField ProfessorPhone;
    private javax.swing.JTextField ProfessorRecord;
    private javax.swing.JTextField ProfessorSalary;
    private javax.swing.JTextField ProfessorSubject;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
