/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

public class ProfessorList extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorList
     */
    public ProfessorList() {
        initComponents();
        setTitle("Listagem de Professores");
        getContentPane().setBackground(new Color(235,237,255));
        
        searchProfessorList();
        if (ProfessorTable.getRowCount() == 0)
            JOptionPane.showMessageDialog(null, "No momento não há professores cadastrados.", "Listar Professores", INFORMATION_MESSAGE);
        else
            DeleteButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProfessorTable = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        BackBotton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 117, 186));
        jLabel1.setText("Listagem dos Professores Cadastrados");

        ProfessorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Nascimento", "CPF", "Matrícula", "Disciplina", "Salário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProfessorTable);

        DeleteButton.setBackground(new java.awt.Color(243, 243, 243));
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-excluir.png"))); // NOI18N
        DeleteButton.setText("Excluir");
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackBotton.setBackground(new java.awt.Color(243, 243, 243));
        BackBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-voltar.png"))); // NOI18N
        BackBotton.setText("Voltar");
        BackBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackBotton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteButton)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton)
                    .addComponent(BackBotton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void searchProfessorList(){
        ConexaoMySQL conection = new ConexaoMySQL();
        Connection conexao = conection.realizaConexao();
        
        DefaultTableModel Table = (DefaultTableModel) ProfessorTable.getModel();
        
        while (Table.getRowCount() > 0)
            Table.removeRow(0);
        
        try {
            String sql_select_professor_list = "SELECT * FROM ementorplus.pessoa, ementorplus.professor where professor.CPF = pessoa.CPF";
            PreparedStatement Atuador_select_professor_list = conexao.prepareStatement(sql_select_professor_list);
            ResultSet Result_select = Atuador_select_professor_list.executeQuery();
            
            while (Result_select.next()){
                Table.addRow(new Object [] {Result_select.getString("Nome"), Result_select.getString("DataNascimento"), Result_select.getString("CPF"), Result_select.getString("Matricula"), Result_select.getString("Disciplina"), Result_select.getDouble("Salario")});
            }
            
            Result_select.close();
            Atuador_select_professor_list.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Algum imprevisto ocorreu "+e+"","ERRO", JOptionPane.ERROR_MESSAGE);
        }
        conection.desconectaMySQL(conexao);
    }
    
    private void BackBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBottonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackBottonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        if (ProfessorTable.getSelectedRow() != -1){
            ConexaoMySQL conection = new ConexaoMySQL();
            int line = ProfessorTable.getSelectedRow();
            String CPF = (ProfessorTable.getModel().getValueAt(line, 2).toString());
            int option = JOptionPane.showConfirmDialog(null, "Deseja deletar o professor ?", "Excluir Professor", YES_NO_OPTION);
            
            if (option == JOptionPane.YES_OPTION){
                conection.RemoveStudent(CPF);
                ((DefaultTableModel) ProfessorTable.getModel()).removeRow(ProfessorTable.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Professor Excluido com Sucesso.", "Excluir Professor", WARNING_MESSAGE);
                conection.RemovePerson(CPF);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "É necessário selecionar um professor para exclusão.", "Excluir Professor", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBotton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTable ProfessorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
