/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author isado
 */
public class StudentEdit extends javax.swing.JFrame {
private Student person = new Student();
private People personFind = new People();

    /**
     * Creates new form EditStudent
     */
    public StudentEdit() {
        initComponents();
        setTitle("Editar Dados do Aluno");
        getContentPane().setBackground(new Color(235,237,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        StudentName = new javax.swing.JTextField();
        BothParents = new javax.swing.JRadioButton();
        Mother = new javax.swing.JRadioButton();
        Father = new javax.swing.JRadioButton();
        StudentMotherName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        StudentFatherName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        StudentBirthday = new javax.swing.JFormattedTextField();
        StudentCPF = new javax.swing.JFormattedTextField();
        StudentPhone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        StudentRecord = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        StudentSchoolYear = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        StudentClass = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        StudentNameSearch = new javax.swing.JTextField();
        SeachrButton = new javax.swing.JButton();
        BackBotton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel22.setForeground(new java.awt.Color(240, 0, 0));
        jLabel22.setText("*");
        jLabel22.setEnabled(false);

        jLabel25.setText("Nome Completo:");
        jLabel25.setEnabled(false);

        jLabel23.setForeground(new java.awt.Color(240, 0, 0));
        jLabel23.setText("*");
        jLabel23.setEnabled(false);

        jLabel27.setText("Data Nascimento:");
        jLabel27.setEnabled(false);

        jLabel24.setForeground(new java.awt.Color(240, 0, 0));
        jLabel24.setText("*");
        jLabel24.setEnabled(false);

        jLabel18.setText("CPF:");
        jLabel18.setEnabled(false);

        jLabel26.setForeground(new java.awt.Color(240, 0, 0));
        jLabel26.setText("*");
        jLabel26.setEnabled(false);

        jLabel19.setText("Telefone/Celular:");
        jLabel19.setEnabled(false);

        StudentName.setEditable(false);

        BothParents.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(BothParents);
        BothParents.setText("Pai e Mãe");
        BothParents.setEnabled(false);
        BothParents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BothParentsMouseClicked(evt);
            }
        });
        BothParents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BothParentsActionPerformed(evt);
            }
        });

        Mother.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Mother);
        Mother.setText("Apenas Mãe");
        Mother.setEnabled(false);
        Mother.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MotherMouseClicked(evt);
            }
        });
        Mother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherActionPerformed(evt);
            }
        });

        Father.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Father);
        Father.setText("Apenas Pai");
        Father.setEnabled(false);
        Father.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FatherMouseClicked(evt);
            }
        });

        StudentMotherName.setEditable(false);

        jLabel28.setText("Nome da Mãe:");
        jLabel28.setEnabled(false);

        jLabel29.setForeground(new java.awt.Color(240, 0, 0));
        jLabel29.setText("*");
        jLabel29.setEnabled(false);

        StudentFatherName.setEditable(false);

        jLabel30.setText("Nome do Pai:");
        jLabel30.setEnabled(false);

        jLabel31.setForeground(new java.awt.Color(240, 0, 0));
        jLabel31.setText("*");
        jLabel31.setEnabled(false);

        jLabel32.setText("Selecione uma opção:");
        jLabel32.setEnabled(false);

        StudentBirthday.setEditable(false);
        try {
            StudentBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        StudentCPF.setEditable(false);
        try {
            StudentCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        StudentCPF.setEnabled(false);

        StudentPhone.setEditable(false);
        try {
            StudentPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BothParents)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel32)
                            .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(StudentBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(StudentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(StudentCPF)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Mother)
                            .addGap(37, 37, 37)
                            .addComponent(Father))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(StudentMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StudentFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BothParents)
                    .addComponent(Mother)
                    .addComponent(Father))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel23)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel26))
                .addGap(3, 3, 3)
                .addComponent(StudentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Escolares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel33.setForeground(new java.awt.Color(240, 0, 0));
        jLabel33.setText("*");
        jLabel33.setEnabled(false);

        jLabel34.setText("Matrícula:");
        jLabel34.setEnabled(false);

        jLabel37.setForeground(new java.awt.Color(240, 0, 0));
        jLabel37.setText("*");
        jLabel37.setEnabled(false);

        StudentRecord.setEditable(false);

        jLabel44.setText("Ano Escolar");
        jLabel44.setEnabled(false);

        StudentSchoolYear.setEditable(false);

        jLabel45.setText("Turma");
        jLabel45.setEnabled(false);

        StudentClass.setEditable(false);

        jLabel46.setForeground(new java.awt.Color(240, 0, 0));
        jLabel46.setText("*");
        jLabel46.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(StudentSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(StudentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(StudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        NextButton.setBackground(new java.awt.Color(243, 243, 243));
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-concluido.png"))); // NOI18N
        NextButton.setText("Salvar");
        NextButton.setEnabled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(243, 243, 243));
        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-cancelar.png"))); // NOI18N
        CancelButton.setText("Cancelar");
        CancelButton.setEnabled(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 117, 186));
        jLabel1.setText("Editar Dados de Aluno(a)");

        jLabel35.setText("Digite o nome completo do estudante:");

        jLabel36.setForeground(new java.awt.Color(240, 0, 0));
        jLabel36.setText("*");

        SeachrButton.setBackground(new java.awt.Color(243, 243, 243));
        SeachrButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-procurar.png"))); // NOI18N
        SeachrButton.setText("Procurar");
        SeachrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeachrButtonActionPerformed(evt);
            }
        });

        BackBotton.setBackground(new java.awt.Color(243, 243, 243));
        BackBotton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-voltar.png"))); // NOI18N
        BackBotton.setText("Voltar");
        BackBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StudentNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SeachrButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BackBotton))
                            .addComponent(jLabel35))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeachrButton)
                    .addComponent(BackBotton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(NextButton))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BothParentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BothParentsMouseClicked
        jLabel28.setEnabled(true);
        jLabel29.setEnabled(true);
        StudentMotherName.setEditable(true);
        jLabel30.setEnabled(true);
        jLabel31.setEnabled(true);
        StudentFatherName.setEditable(true);
    }//GEN-LAST:event_BothParentsMouseClicked

    private void BothParentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BothParentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BothParentsActionPerformed

    private void MotherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotherMouseClicked
        jLabel28.setEnabled(true);
        jLabel29.setEnabled(true);
        StudentMotherName.setEditable(true);
        jLabel30.setEnabled(false);
        jLabel31.setEnabled(false);
        StudentFatherName.setEditable(false);
        StudentFatherName.setText("");
    }//GEN-LAST:event_MotherMouseClicked

    private void MotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotherActionPerformed

    private void FatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FatherMouseClicked
        jLabel28.setEnabled(false);
        jLabel29.setEnabled(false);
        StudentMotherName.setEditable(false);
        StudentMotherName.setText("");
        jLabel30.setEnabled(true);
        jLabel31.setEnabled(true);
        StudentFatherName.setEditable(true);
    }//GEN-LAST:event_FatherMouseClicked

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if (BothParents.isSelected()){
            if (StudentName.getText().equals("") || StudentMotherName.getText().equals("") || StudentFatherName.getText().equals("") || StudentBirthday.getText().equals("") || StudentCPF.getText().equals("") || StudentPhone.getText().equals("") || StudentRecord.getText().equals("") || StudentSchoolYear.getText().equals("") || StudentClass.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Edição Aluno", WARNING_MESSAGE);
            }
            else {
                ConexaoMySQL conection = new ConexaoMySQL();
                personFind = conection.searchPeople(StudentCPF.getText());
                if (personFind == null){
                    conection.updateStudents(StudentName.getText(), StudentMotherName.getText(), StudentFatherName.getText(), StudentBirthday.getText(), StudentCPF.getText(), StudentPhone.getText(), StudentRecord.getText(), StudentSchoolYear.getText(), StudentClass.getText());
                    JOptionPane.showMessageDialog(null, "Alteração Realizada com Sucesso", "Edição de Aluno", INFORMATION_MESSAGE);
                    setVisible(false);
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!", "Edição de Aluno", ERROR_MESSAGE);
            }
        }
        else if (Mother.isSelected()){
            if (StudentName.getText().equals("") || StudentMotherName.getText().equals("") || StudentBirthday.getText().equals("") || StudentCPF.getText().equals("") || StudentPhone.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Edição Aluno", WARNING_MESSAGE);
            }
            else {
                ConexaoMySQL conection = new ConexaoMySQL();
                personFind = conection.searchPeople(StudentCPF.getText());
                if (personFind == null){
                    conection.updateStudents(StudentName.getText(), StudentMotherName.getText(), StudentFatherName.getText(), StudentBirthday.getText(), StudentCPF.getText(), StudentPhone.getText(), StudentRecord.getText(), StudentSchoolYear.getText(), StudentClass.getText());
                    JOptionPane.showMessageDialog(null, "Alteração Realizada com Sucesso", "Edição de Aluno", INFORMATION_MESSAGE);
                    setVisible(false);
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!", "Edição de Aluno", ERROR_MESSAGE);
            }
        }
        else if (Father.isSelected()){
            if (StudentName.getText().equals("") || StudentFatherName.getText().equals("") || StudentBirthday.getText().equals("") || StudentCPF.getText().equals("") || StudentPhone.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Edição Aluno", WARNING_MESSAGE);
            }
            else {
                ConexaoMySQL conection = new ConexaoMySQL();
                personFind = conection.searchPeople(StudentCPF.getText());
                if (personFind == null){
                    conection.updateStudents(StudentName.getText(), StudentMotherName.getText(), StudentFatherName.getText(), StudentBirthday.getText(), StudentCPF.getText(), StudentPhone.getText(), StudentRecord.getText(), StudentSchoolYear.getText(), StudentClass.getText());
                    JOptionPane.showMessageDialog(null, "Alteração Realizada com Sucesso", "Edição de Aluno", INFORMATION_MESSAGE);
                    setVisible(false);
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!", "Edição de Aluno", ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem preenchidos!", "Edição Aluno", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_NextButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        StudentName.setText("");
        StudentMotherName.setText("");
        StudentFatherName.setText("");
        StudentBirthday.setText("");
        StudentCPF.setText("");
        StudentPhone.setText("");
        StudentRecord.setText("");
        StudentSchoolYear.setText("");
        StudentClass.setText("");
        
        StudentName.setEditable(false);
        StudentMotherName.setEditable(false);
        StudentFatherName.setEditable(false);
        StudentBirthday.setEditable(false);
        StudentPhone.setEditable(false);
        StudentRecord.setEditable(false);
        StudentSchoolYear.setEditable(false);
        StudentClass.setEditable(false);

        jLabel22.setEnabled(false);
        jLabel23.setEnabled(false);
        jLabel24.setEnabled(false);
        jLabel25.setEnabled(false);
        jLabel26.setEnabled(false);
        jLabel27.setEnabled(false);
        jLabel28.setEnabled(false);
        jLabel29.setEnabled(false);
        jLabel30.setEnabled(false);
        jLabel31.setEnabled(false);
        jLabel32.setEnabled(false);
        jLabel33.setEnabled(false);
        jLabel34.setEnabled(false);
        jLabel37.setEnabled(false);
        jLabel44.setEnabled(false);
        jLabel45.setEnabled(false);
        jLabel46.setEnabled(false);
        jLabel18.setEnabled(false);
        jLabel19.setEnabled(false);

        NextButton.setEnabled(false);
        CancelButton.setEnabled(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void BackBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBottonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackBottonActionPerformed

    private void SeachrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeachrButtonActionPerformed
        if (StudentNameSearch.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo não preenchido!", "Editar Dados do Aluno", WARNING_MESSAGE);
        }
        else {
            ConexaoMySQL conection = new ConexaoMySQL();
            person = conection.searchStudent(StudentNameSearch.getText());
            
            if (person != null){
                if (person.getNomeMae().equals("")){
                    StudentFatherName.setText(person.getNomePai());
                    StudentFatherName.setEditable(true);
                    jLabel30.setEnabled(true);
                    jLabel31.setEnabled(true);
                }
                else if (person.getNomePai().equals("")){
                    StudentMotherName.setText(person.getNomeMae());
                    StudentMotherName.setEditable(true);
                    jLabel28.setEnabled(true);
                    jLabel29.setEnabled(true);
                }
                else {
                    StudentMotherName.setText(person.getNomeMae());
                    StudentMotherName.setEditable(true);
                    StudentFatherName.setText(person.getNomePai());
                    StudentFatherName.setEditable(true);
                    jLabel28.setEnabled(true);
                    jLabel29.setEnabled(true);
                    jLabel30.setEnabled(true);
                    jLabel31.setEnabled(true);
                }
                
                StudentName.setText(person.getNome());
                StudentBirthday.setText(person.getDataNascimento());
                StudentCPF.setText(person.getCPF());
                StudentPhone.setText(person.getTelefone());
                StudentRecord.setText(person.getMatricula());
                StudentSchoolYear.setText(person.getAnoEscolar());
                StudentClass.setText(person.getTurma());
                
                StudentName.setEditable(true);
                StudentBirthday.setEditable(true);
                StudentPhone.setEditable(true);
                StudentRecord.setEditable(true);
                StudentSchoolYear.setEditable(true);
                StudentClass.setEditable(true);
                
                BothParents.setEnabled(true);
                Mother.setEnabled(true);
                Father.setEnabled(true);
                
                jLabel22.setEnabled(true);
                jLabel23.setEnabled(true);
                jLabel24.setEnabled(true);
                jLabel25.setEnabled(true);
                jLabel26.setEnabled(true);
                jLabel27.setEnabled(true);
                jLabel32.setEnabled(true);
                jLabel33.setEnabled(true);
                jLabel34.setEnabled(true);
                jLabel37.setEnabled(true);
                jLabel44.setEnabled(true);
                jLabel45.setEnabled(true);
                jLabel46.setEnabled(true);
                jLabel18.setEnabled(true);
                jLabel19.setEnabled(true);
                
                NextButton.setEnabled(true);
                CancelButton.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Aluno não encontrado","Alteração de Dados do Aluno",ERROR_MESSAGE);
                StudentNameSearch.setText("");
            }
        }
    }//GEN-LAST:event_SeachrButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBotton;
    private javax.swing.JRadioButton BothParents;
    private javax.swing.JButton CancelButton;
    private javax.swing.JRadioButton Father;
    private javax.swing.JRadioButton Mother;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton SeachrButton;
    private javax.swing.JFormattedTextField StudentBirthday;
    private javax.swing.JFormattedTextField StudentCPF;
    private javax.swing.JTextField StudentClass;
    private javax.swing.JTextField StudentFatherName;
    private javax.swing.JTextField StudentMotherName;
    private javax.swing.JTextField StudentName;
    private javax.swing.JTextField StudentNameSearch;
    private javax.swing.JFormattedTextField StudentPhone;
    private javax.swing.JTextField StudentRecord;
    private javax.swing.JTextField StudentSchoolYear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
